
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: youtube-tv-client
  version: '2.0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Basically a browser that uses Samsung Smart TV as the user agent and goes to youtube.com/tv
  description: |
    Made from NodeJS and Electron

    Navigating the website

    - Use the arrows on the keyboard to navigate
    - Press ESC to exit or to go back
    - Press enter to select

  grade: edge # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
